version: '3.9'
services:
  web:
    image: nginx:alpine
    ports:
      -  ${PORT}:80
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/dino.wasm:/usr/share/nginx/html/dino.wasm
    restart: unless-stopped